export const ToDo = {
  GET_TODO: 'GET_TODO',
  FAIL_TODO: 'FAIL_TODO',
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  DETAIL_TODO: 'DETAIL_TODO',
  DETAILFAIL_TODO: 'DETAILFAIL_TODO',
};
